--crete the schema to the dbo user
CREATE SCHEMA contraincendiosh
AUTHORIZATION dbo

-- Drop the table if it already exists
IF OBJECT_ID('contraincendiosh.bodegas', 'U') IS NOT NULL
DROP TABLE rci.bodegas
GO

-- Create bodegas in rci
CREATE TABLE contraincendiosh.bodegas
(
	id INT IDENTITY(1,1),
	name NVARCHAR(50) NOT NULL,
	latitude DECIMAL(10,7) NOT NULL,
	longitude DECIMAL(10,7) NOT NULL,
	tipo NVARCHAR(50) NOT NULL
);
GO




CREATE TABLE temptable (
    ID INT,
    FECHA DATE,
    EMPRESA VARCHAR(255),
    VICEPRESIDENCIA VARCHAR(255),
    GERENCIA_DEPTO VARCHAR(255),
    CODIGO_PEC VARCHAR(255),
    EXPEDIENTE_LAM VARCHAR(255),
    BASE_RESPUESTA_INDICADA_PEC VARCHAR(255),
    FUNCIONARIO_CONTACTO VARCHAR(255),
    CORREO_FUNCIONARIO_CONTACTO VARCHAR(255),
    CORREO_DILIGENCIA_FORMATO VARCHAR(255),
    NOMBRE_BODEGA VARCHAR(255),
    TIPO_BODEGA VARCHAR(255),
    LATITUD VARCHAR(255),
    LONGITUD VARCHAR(255),
    ACTIVIDAD_APLICACION VARCHAR(255),
    NOMBRE_EQUIPO VARCHAR(255),
    FABRICANTE VARCHAR(255),
    ESPECIFICACIONES_EQUIPO VARCHAR(255),
    UNIDAD VARCHAR(255),
    CANTIDAD INT,
    FACILIDAD_SISTEMA_TRANSPORTE_CAMPO VARCHAR(255),
    INSTALACION VARCHAR(255),
    CODIGO_IDENTIFICACION_INVENTARIO VARCHAR(255),
    ESTADO_TEORICO_REPORTADO VARCHAR(255),
    OBSERVACIONES VARCHAR(255),
    TIPO_ELEMENTO VARCHAR(255),
    RUTA_ACCESO VARCHAR(255)
);
GO

SELECT * FROM contraincendiosh.ogisData

BULK INSERT temptable
FROM 'C:\Users\afrok\OneDrive\Escritorio\SigHums\EcoAzure\export_equipos&bodegasOGI_cop.csv'
WITH(
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n'
)
GO


INSERT INTO contraincendiosh.bodegas (name,latitude,longitude,tipo) VALUES ('Bodega C.I. Yondo','7.003304','-73.911276','fija');
SELECT * FROM contraincendiosh.bodegas;